pipeline:
  test:
    image: swhurl/node-with-deps:8-alpine
    commands:
      - yarn install
      - npm test 
  publish:
    image: plugins/docker
    repo: swhurl/website
    build_args:
      - target=production
    force_tag: true
    tags:
      - latest
    secrets: [docker_username, docker_password]
    when:
      branch: master
