pipeline:

  build:
    image: michalpodeszwa/docker-compose:latest 
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker-compose -f docker-compose.test.yml up -d --build
    when:
      event: [ push, tag ]
        
  test:
    image: michalpodeszwa/docker-compose:latest 
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker-compose -f docker-compose.test.yml run test npm test
    when:
      event: [ push, tag ]

  cleanup:
    image: michalpodeszwa/docker-compose:latest 
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker-compose -f docker-compose.test.yml rm -f
      - docker-compose -f docker-compose.test.yml down
    when:
      event: [ push, tag ]
      status: [ success, failure ]

  publish-staging:
    image: plugins/docker
    repo: swhurl/website
    build_args:
      - DRONE_COMMIT=${DRONE_COMMIT}
    force_tag: true
    tags:
      - staging
    secrets: [docker_username, docker_password]
    when:
      branch: [ master ]
      event: [ push ]

  deploy-staging:
    image: appleboy/drone-ssh
    host: swhurl.com
    port: 22
    secrets: [ ssh_username, ssh_password ]
    script:
      - docker pull swhurl/website:staging
      - docker stop website-staging
      - docker rm website-staging
      - docker run --name website-staging --net swhurl --restart always -d swhurl/website:staging 
    when:
      event: deployment
      environment: staging

  publish-production:
    image: plugins/docker
    repo: swhurl/website
    build_args:
      - DRONE_COMMIT=$DRONE_COMMIT
    force_tag: true
    tags:
      - ${DRONE_TAG##v}
    secrets: [docker_username, docker_password]
    when:
      event: [ tag ]

  deploy-production:
    image: appleboy/drone-ssh
    host: swhurl.com
    username: sam
    port: 22
    secrets: [ssh_key]
    script:
      - docker stop website
      - docker rm website
      - docker pull swhurl/website:$DRONE_TAG
      - docker run --name website --net swhurl --restart always -d swhurl/website:$DRONE_TAG 
    when:
      event: deployment
      environment: production

