pipeline:

  build:
    image: michalpodeszwa/docker-compose:latest 
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker-compose -f docker-compose.test.yml up -d --build
    when:
      event: [ push, tag ]
        
  test:
    image: michalpodeszwa/docker-compose:latest 
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker-compose -f docker-compose.test.yml run test npm test
    when:
      event: [ push, tag ]

  cleanup:
    image: michalpodeszwa/docker-compose:latest 
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker-compose -f docker-compose.test.yml rm -f
      - docker-compose -f docker-compose.test.yml down
    when:
      event: [ push, tag ]
      status: [ success, failure ]

  publish-staging:
    secrets: [ docker_username, docker_password ]
    image: docker
    privileged: true
    environment:
      - DOCKER_HOST=unix:///drone/docker.sock
    commands:
      - env
      - echo ${DOCKER_USERNAME}
      - ./publish.sh staging
    when:
      branch: [ master ]
      event: [ push, deployment ]

  deploy-staging:
    image: appleboy/drone-ssh
    host: swhurl.com
    port: 22
    secrets: [ ssh_username, ssh_password ]
    script:
      - docker pull registry.swhurl.com/swhurl/website:staging
      - docker stop website-staging
      - docker rm website-staging
      - docker run --name website-staging --net swhurl --restart always -d registry.swhurl.com/swhurl/website:staging 
    when:
      branch: [ master ]
      event: [ push ]

  publish-production:
    secrets: [ docker_username, docker_password ]
    image: docker
    privileged: true
    environment:
      - DOCKER_HOST=unix:///drone/docker.sock
    commands:
      - ./publish.sh production
    when:
      event: [ tag ]

  deploy-production:
    image: appleboy/drone-ssh
    host: swhurl.com
    username: sam
    port: 22
    secrets: [ ssh_username, ssh_password ]
    script:
      - docker pull registry.swhurl.com/swhurl/website:${DRONE_TAG##v}
      - docker stop website
      - docker rm website
      - docker run --name website --net swhurl --restart always -d registry.swhurl.com/swhurl/website:${DRONE_TAG##v} 
    when:
      event: [ tag ]

services:
  docker:
    image: docker:dind
    privileged: true
    command: [ '-H', 'unix:///drone/docker.sock' ]
