pipeline:
  test:
    image: node:8-alpine
    commands:
      - npm i
      - npm test
  publish:
    image: plugins/docker
    repo: swhurl/website
    tags:
      - latest
      - 1.0.0
      - 1.0
    secrets: [docker_username, docker_password]
