version: 2
jobs:
  build_test: 
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          echo -e "commit: $CIRCLE_SHA1\ntag: $CIRCLE_TAG" > ./version.txt
      - run:
          name: Install Docker Compose
          command: |
            set -x
            curl -L https://github.com/docker/compose/releases/download/1.18.0/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
            chmod +x /usr/local/bin/docker-compose
            curl -fsSL https://get.docker.com -o get-docker.sh
            sh get-docker.sh
      - run: |
          docker-compose build
          docker-compose up --exit-code-from test
          docker cp project_test_1:/www/test/output /output/
      - store_artifacts:
          path: /output
      - store_test_results:
          path: /output/junit/
      - run: |
          if [[ "$CIRCLE_BRANCH" = "master" ]]
          then
              set -x
              VER="18.06.3-ce"
              curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
              tar -xz -C /tmp -f /tmp/docker-$VER.tgz
              mv /tmp/docker/* /usr/bin
              echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
              docker push swhurl/mf-website:$CIRCLE_SHA1
          fi
        
workflows:
  version: 2
  build_test_push_deploy:
    jobs:
      - build_test
