version: 2
jobs:
  build_test: 
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: |
          echo -e "commit: $CIRCLE_SHA1\ntag: $CIRCLE_TAG" > ./version.txt
      - run:
          name: Install Docker Compose
          command: |
            set -x
            curl -L https://github.com/docker/compose/releases/download/1.18.0/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
            chmod +x /usr/local/bin/docker-compose
      - run: |
          docker-compose build
          docker-compose up --exit-code-from test
      - run: |
          if [[ "$CIRCLE_BRANCH" = "master" ]]
          then
              set -x
              VER="18.06.3-ce"
              curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
              tar -xz -C /tmp -f /tmp/docker-$VER.tgz
              mv /tmp/docker/* /usr/bin
              echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
              docker push swhurl/website:$CIRCLE_SHA1
          fi
  deploy_staging:
    machine: true
    steps:
      - add_ssh_keys:
          fingerprints: 
            - "35:df:e3:cc:13:79:99:24:29:2f:39:b4:8b:5a:0a:14"
      - run: |
          echo "staging: branch == master"
          echo "sha1: '$CIRCLE_SHA1'"
          echo "tag: '$CIRCLE_TAG'"
          echo "deploy: swhurl/website:$CIRCLE_SHA1"
          ssh $SSH_USER@$SSH_HOST "kubectl get deployment swhurl-website-staging -o yaml | sed -r 's/website:(.*)/website:$CIRCLE_SHA1/g' | kubectl apply -f -"
  deploy_prod:
    machine: true
    steps:
      - add_ssh_keys:
          fingerprints: 
            - "35:df:e3:cc:13:79:99:24:29:2f:39:b4:8b:5a:0a:14"
      - run: |
          echo "production: tag == $CIRCLE_TAG"
          echo "sha1: '$CIRCLE_SHA1'"
          echo "tag: '$CIRCLE_TAG'"
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
          docker pull swhurl/website:$CIRCLE_SHA1
          docker tag swhurl/website:$CIRCLE_SHA1 swhurl/website:${CIRCLE_TAG##v}
          docker push swhurl/website:${CIRCLE_TAG##v}
          echo "deploy swhurl/website:${CIRCLE_TAG##v}"
          ssh $SSH_USER@$SSH_HOST "kubectl get deployment swhurl-website -o yaml | sed -r 's/website:(.*)/website:${CIRCLE_TAG##v}/g' | kubectl apply -f -"
  release_tag:
    machine: true
    steps:
      - run: |
          echo "deploy swhurl/website:${CIRCLE_TAG}"
          ssh $SSH_USER@$SSH_HOST "kubectl get deployment swhurl-website -o yaml | sed -r 's/website:(.*)/website:${CIRCLE_TAG}/g' | kubectl apply -f -"
        
workflows:
  version: 2
  build_test_push_deploy:
    jobs:
      - build_test
      - deploy_staging:
          requires:
            - build_test
          filters:
            branches:
              only: 
                - master
      - deploy_prod:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v(.*)/
