apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth2-proxy
spec:
  replicas: 1
  template:
    spec:
      containers:
      - args:
        - --provider=github
        - --email-domain=swhurl.com
        - --upstream=file:///dev/null
        - --http-address=0.0.0.0:4180
        # Register a new application
        # https://github.com/settings/applications/new
        env:
        - name: OAUTH2_PROXY_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: staging-mf-swhurl-website-oauth2-proxy
              key: github_client_id
        - name: OAUTH2_PROXY_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: staging-mf-swhurl-website-oauth2-proxy
              key: github_client_secret
        # docker run -ti --rm python:3-alpine python -c 'import secrets,base64; print(base64.b64encode(base64.b64encode(secrets.token_bytes(16))));'
        - name: OAUTH2_PROXY_COOKIE_SECRET
          valueFrom:
            secretKeyRef:
              name: staging-mf-swhurl-website-oauth2-proxy
              key: cookie_secret
        image: docker.io/colemickens/oauth2_proxy:latest
        imagePullPolicy: Always
        name: mf-swhurl-staging-oauth2-proxy
        ports:
        - containerPort: 4180
          protocol: TCP


