apiVersion: v1
kind: Secret
metadata:
  name: oauth2-proxy
type: Opaque
data:
  github_client_id: NDcwZGUyYTlmNTc1ZWE1NmJhMjI=
  github_client_secret: MmQ5OTliODUxZWFkNzQzNWU1NDJmYmU0NmUzYjNjNThjODBlNjUzNA== 
  cookie_secret: c2Fka2pmc2FsZGZwOXVzYWwyN3lrYmxmYTg=
