apiVersion: v1
kind: Secret
metadata:
  name: oauth2-proxy
type: Opaque
data:
  github_client_id: <base64_encoded_github_client_id>
  github_client_secret: <base54_encoded_github_client_secret> 
  cookie_secret: <base64_cookie_secret>
